// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/cs/CenterMsg.proto

package com.game.pb;

public final class CenterMsgProto {
  private CenterMsgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ForwardMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 fromServerID = 1;
    /**
     * <code>required int32 fromServerID = 1;</code>
     */
    boolean hasFromServerID();
    /**
     * <code>required int32 fromServerID = 1;</code>
     */
    int getFromServerID();

    // required int32 toServerID = 2;
    /**
     * <code>required int32 toServerID = 2;</code>
     */
    boolean hasToServerID();
    /**
     * <code>required int32 toServerID = 2;</code>
     */
    int getToServerID();

    // optional int32 userID = 3;
    /**
     * <code>optional int32 userID = 3;</code>
     */
    boolean hasUserID();
    /**
     * <code>optional int32 userID = 3;</code>
     */
    int getUserID();

    // optional bytes packet = 4;
    /**
     * <code>optional bytes packet = 4;</code>
     */
    boolean hasPacket();
    /**
     * <code>optional bytes packet = 4;</code>
     */
    com.google.protobuf.ByteString getPacket();
  }
  /**
   * Protobuf type {@code com.game.proto.ForwardMsg}
   */
  public static final class ForwardMsg extends
      com.google.protobuf.GeneratedMessage
      implements ForwardMsgOrBuilder {
    // Use ForwardMsg.newBuilder() to construct.
    private ForwardMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ForwardMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ForwardMsg defaultInstance;
    public static ForwardMsg getDefaultInstance() {
      return defaultInstance;
    }

    public ForwardMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ForwardMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              fromServerID_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              toServerID_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              userID_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              packet_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.pb.CenterMsgProto.internal_static_com_game_proto_ForwardMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.pb.CenterMsgProto.internal_static_com_game_proto_ForwardMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.pb.CenterMsgProto.ForwardMsg.class, com.game.pb.CenterMsgProto.ForwardMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<ForwardMsg> PARSER =
        new com.google.protobuf.AbstractParser<ForwardMsg>() {
      public ForwardMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ForwardMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ForwardMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 fromServerID = 1;
    public static final int FROMSERVERID_FIELD_NUMBER = 1;
    private int fromServerID_;
    /**
     * <code>required int32 fromServerID = 1;</code>
     */
    public boolean hasFromServerID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 fromServerID = 1;</code>
     */
    public int getFromServerID() {
      return fromServerID_;
    }

    // required int32 toServerID = 2;
    public static final int TOSERVERID_FIELD_NUMBER = 2;
    private int toServerID_;
    /**
     * <code>required int32 toServerID = 2;</code>
     */
    public boolean hasToServerID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 toServerID = 2;</code>
     */
    public int getToServerID() {
      return toServerID_;
    }

    // optional int32 userID = 3;
    public static final int USERID_FIELD_NUMBER = 3;
    private int userID_;
    /**
     * <code>optional int32 userID = 3;</code>
     */
    public boolean hasUserID() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 userID = 3;</code>
     */
    public int getUserID() {
      return userID_;
    }

    // optional bytes packet = 4;
    public static final int PACKET_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString packet_;
    /**
     * <code>optional bytes packet = 4;</code>
     */
    public boolean hasPacket() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes packet = 4;</code>
     */
    public com.google.protobuf.ByteString getPacket() {
      return packet_;
    }

    private void initFields() {
      fromServerID_ = 0;
      toServerID_ = 0;
      userID_ = 0;
      packet_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasFromServerID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasToServerID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, fromServerID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, toServerID_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, userID_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, packet_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, fromServerID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, toServerID_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, userID_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, packet_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.game.pb.CenterMsgProto.ForwardMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.pb.CenterMsgProto.ForwardMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.pb.CenterMsgProto.ForwardMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.pb.CenterMsgProto.ForwardMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.pb.CenterMsgProto.ForwardMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.pb.CenterMsgProto.ForwardMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.game.pb.CenterMsgProto.ForwardMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.game.pb.CenterMsgProto.ForwardMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.game.pb.CenterMsgProto.ForwardMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.pb.CenterMsgProto.ForwardMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.pb.CenterMsgProto.ForwardMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.game.proto.ForwardMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game.pb.CenterMsgProto.ForwardMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.pb.CenterMsgProto.internal_static_com_game_proto_ForwardMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.pb.CenterMsgProto.internal_static_com_game_proto_ForwardMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.pb.CenterMsgProto.ForwardMsg.class, com.game.pb.CenterMsgProto.ForwardMsg.Builder.class);
      }

      // Construct using com.game.pb.CenterMsgProto.ForwardMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        fromServerID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        toServerID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        userID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        packet_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.pb.CenterMsgProto.internal_static_com_game_proto_ForwardMsg_descriptor;
      }

      public com.game.pb.CenterMsgProto.ForwardMsg getDefaultInstanceForType() {
        return com.game.pb.CenterMsgProto.ForwardMsg.getDefaultInstance();
      }

      public com.game.pb.CenterMsgProto.ForwardMsg build() {
        com.game.pb.CenterMsgProto.ForwardMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.pb.CenterMsgProto.ForwardMsg buildPartial() {
        com.game.pb.CenterMsgProto.ForwardMsg result = new com.game.pb.CenterMsgProto.ForwardMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fromServerID_ = fromServerID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.toServerID_ = toServerID_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.userID_ = userID_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.packet_ = packet_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.pb.CenterMsgProto.ForwardMsg) {
          return mergeFrom((com.game.pb.CenterMsgProto.ForwardMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.pb.CenterMsgProto.ForwardMsg other) {
        if (other == com.game.pb.CenterMsgProto.ForwardMsg.getDefaultInstance()) return this;
        if (other.hasFromServerID()) {
          setFromServerID(other.getFromServerID());
        }
        if (other.hasToServerID()) {
          setToServerID(other.getToServerID());
        }
        if (other.hasUserID()) {
          setUserID(other.getUserID());
        }
        if (other.hasPacket()) {
          setPacket(other.getPacket());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFromServerID()) {
          
          return false;
        }
        if (!hasToServerID()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.pb.CenterMsgProto.ForwardMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.pb.CenterMsgProto.ForwardMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 fromServerID = 1;
      private int fromServerID_ ;
      /**
       * <code>required int32 fromServerID = 1;</code>
       */
      public boolean hasFromServerID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 fromServerID = 1;</code>
       */
      public int getFromServerID() {
        return fromServerID_;
      }
      /**
       * <code>required int32 fromServerID = 1;</code>
       */
      public Builder setFromServerID(int value) {
        bitField0_ |= 0x00000001;
        fromServerID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 fromServerID = 1;</code>
       */
      public Builder clearFromServerID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fromServerID_ = 0;
        onChanged();
        return this;
      }

      // required int32 toServerID = 2;
      private int toServerID_ ;
      /**
       * <code>required int32 toServerID = 2;</code>
       */
      public boolean hasToServerID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 toServerID = 2;</code>
       */
      public int getToServerID() {
        return toServerID_;
      }
      /**
       * <code>required int32 toServerID = 2;</code>
       */
      public Builder setToServerID(int value) {
        bitField0_ |= 0x00000002;
        toServerID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 toServerID = 2;</code>
       */
      public Builder clearToServerID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        toServerID_ = 0;
        onChanged();
        return this;
      }

      // optional int32 userID = 3;
      private int userID_ ;
      /**
       * <code>optional int32 userID = 3;</code>
       */
      public boolean hasUserID() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 userID = 3;</code>
       */
      public int getUserID() {
        return userID_;
      }
      /**
       * <code>optional int32 userID = 3;</code>
       */
      public Builder setUserID(int value) {
        bitField0_ |= 0x00000004;
        userID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 userID = 3;</code>
       */
      public Builder clearUserID() {
        bitField0_ = (bitField0_ & ~0x00000004);
        userID_ = 0;
        onChanged();
        return this;
      }

      // optional bytes packet = 4;
      private com.google.protobuf.ByteString packet_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes packet = 4;</code>
       */
      public boolean hasPacket() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes packet = 4;</code>
       */
      public com.google.protobuf.ByteString getPacket() {
        return packet_;
      }
      /**
       * <code>optional bytes packet = 4;</code>
       */
      public Builder setPacket(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        packet_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes packet = 4;</code>
       */
      public Builder clearPacket() {
        bitField0_ = (bitField0_ & ~0x00000008);
        packet_ = getDefaultInstance().getPacket();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.game.proto.ForwardMsg)
    }

    static {
      defaultInstance = new ForwardMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.game.proto.ForwardMsg)
  }

  public interface RegisterMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 serverID = 1;
    /**
     * <code>required int32 serverID = 1;</code>
     */
    boolean hasServerID();
    /**
     * <code>required int32 serverID = 1;</code>
     */
    int getServerID();
  }
  /**
   * Protobuf type {@code com.game.proto.RegisterMsg}
   */
  public static final class RegisterMsg extends
      com.google.protobuf.GeneratedMessage
      implements RegisterMsgOrBuilder {
    // Use RegisterMsg.newBuilder() to construct.
    private RegisterMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RegisterMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RegisterMsg defaultInstance;
    public static RegisterMsg getDefaultInstance() {
      return defaultInstance;
    }

    public RegisterMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RegisterMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              serverID_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.pb.CenterMsgProto.internal_static_com_game_proto_RegisterMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.pb.CenterMsgProto.internal_static_com_game_proto_RegisterMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.pb.CenterMsgProto.RegisterMsg.class, com.game.pb.CenterMsgProto.RegisterMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<RegisterMsg> PARSER =
        new com.google.protobuf.AbstractParser<RegisterMsg>() {
      public RegisterMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RegisterMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RegisterMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 serverID = 1;
    public static final int SERVERID_FIELD_NUMBER = 1;
    private int serverID_;
    /**
     * <code>required int32 serverID = 1;</code>
     */
    public boolean hasServerID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 serverID = 1;</code>
     */
    public int getServerID() {
      return serverID_;
    }

    private void initFields() {
      serverID_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasServerID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, serverID_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, serverID_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.game.pb.CenterMsgProto.RegisterMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.pb.CenterMsgProto.RegisterMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.pb.CenterMsgProto.RegisterMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.pb.CenterMsgProto.RegisterMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.pb.CenterMsgProto.RegisterMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.pb.CenterMsgProto.RegisterMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.game.pb.CenterMsgProto.RegisterMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.game.pb.CenterMsgProto.RegisterMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.game.pb.CenterMsgProto.RegisterMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.pb.CenterMsgProto.RegisterMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.pb.CenterMsgProto.RegisterMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.game.proto.RegisterMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game.pb.CenterMsgProto.RegisterMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.pb.CenterMsgProto.internal_static_com_game_proto_RegisterMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.pb.CenterMsgProto.internal_static_com_game_proto_RegisterMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.pb.CenterMsgProto.RegisterMsg.class, com.game.pb.CenterMsgProto.RegisterMsg.Builder.class);
      }

      // Construct using com.game.pb.CenterMsgProto.RegisterMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serverID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.pb.CenterMsgProto.internal_static_com_game_proto_RegisterMsg_descriptor;
      }

      public com.game.pb.CenterMsgProto.RegisterMsg getDefaultInstanceForType() {
        return com.game.pb.CenterMsgProto.RegisterMsg.getDefaultInstance();
      }

      public com.game.pb.CenterMsgProto.RegisterMsg build() {
        com.game.pb.CenterMsgProto.RegisterMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.pb.CenterMsgProto.RegisterMsg buildPartial() {
        com.game.pb.CenterMsgProto.RegisterMsg result = new com.game.pb.CenterMsgProto.RegisterMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serverID_ = serverID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.pb.CenterMsgProto.RegisterMsg) {
          return mergeFrom((com.game.pb.CenterMsgProto.RegisterMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.pb.CenterMsgProto.RegisterMsg other) {
        if (other == com.game.pb.CenterMsgProto.RegisterMsg.getDefaultInstance()) return this;
        if (other.hasServerID()) {
          setServerID(other.getServerID());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasServerID()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.pb.CenterMsgProto.RegisterMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.pb.CenterMsgProto.RegisterMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 serverID = 1;
      private int serverID_ ;
      /**
       * <code>required int32 serverID = 1;</code>
       */
      public boolean hasServerID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 serverID = 1;</code>
       */
      public int getServerID() {
        return serverID_;
      }
      /**
       * <code>required int32 serverID = 1;</code>
       */
      public Builder setServerID(int value) {
        bitField0_ |= 0x00000001;
        serverID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 serverID = 1;</code>
       */
      public Builder clearServerID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverID_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.game.proto.RegisterMsg)
    }

    static {
      defaultInstance = new RegisterMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.game.proto.RegisterMsg)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_proto_ForwardMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_game_proto_ForwardMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_proto_RegisterMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_game_proto_RegisterMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030proto/cs/CenterMsg.proto\022\016com.game.pro" +
      "to\"V\n\nForwardMsg\022\024\n\014fromServerID\030\001 \002(\005\022\022" +
      "\n\ntoServerID\030\002 \002(\005\022\016\n\006userID\030\003 \001(\005\022\016\n\006pa" +
      "cket\030\004 \001(\014\"\037\n\013RegisterMsg\022\020\n\010serverID\030\001 " +
      "\002(\005B\035\n\013com.game.pbB\016CenterMsgProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_game_proto_ForwardMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_game_proto_ForwardMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_game_proto_ForwardMsg_descriptor,
              new java.lang.String[] { "FromServerID", "ToServerID", "UserID", "Packet", });
          internal_static_com_game_proto_RegisterMsg_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_game_proto_RegisterMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_game_proto_RegisterMsg_descriptor,
              new java.lang.String[] { "ServerID", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
