// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/command/ProtocolOut.proto

package com.game.pb.command;

public final class ProtocolOutProto {
  private ProtocolOutProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.game.proto.ProtocolOut}
   */
  public enum ProtocolOut
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PING = 20480;</code>
     *
     * <pre>
     * ping
     * </pre>
     */
    PING(0, 20480),
    /**
     * <code>SHUT_DOWN_CMD = 20481;</code>
     *
     * <pre>
     * 停服
     * </pre>
     */
    SHUT_DOWN_CMD(1, 20481),
    ;

    /**
     * <code>PING = 20480;</code>
     *
     * <pre>
     * ping
     * </pre>
     */
    public static final int PING_VALUE = 20480;
    /**
     * <code>SHUT_DOWN_CMD = 20481;</code>
     *
     * <pre>
     * 停服
     * </pre>
     */
    public static final int SHUT_DOWN_CMD_VALUE = 20481;


    public final int getNumber() { return value; }

    public static ProtocolOut valueOf(int value) {
      switch (value) {
        case 20480: return PING;
        case 20481: return SHUT_DOWN_CMD;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ProtocolOut>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ProtocolOut>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ProtocolOut>() {
            public ProtocolOut findValueByNumber(int number) {
              return ProtocolOut.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.game.pb.command.ProtocolOutProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final ProtocolOut[] VALUES = values();

    public static ProtocolOut valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ProtocolOut(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.game.proto.ProtocolOut)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037proto/command/ProtocolOut.proto\022\016com.g" +
      "ame.proto*.\n\013ProtocolOut\022\n\n\004PING\020\200\240\001\022\023\n\r" +
      "SHUT_DOWN_CMD\020\201\240\001B\'\n\023com.game.pb.command" +
      "B\020ProtocolOutProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
